import type { Metadata } from "next";
import { Inter, Lato } from "next/font/google";
import "@/app/assets/globals.css";
import "@/app/assets/fonts.css";

const inter = Inter({ subsets: ["latin"] });

const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Quicks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>{children}</body>
    </html>
  );
}
